[build-system]
requires = ["hatchling>=1.5.0", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "globato"
description = "A suite of specialized data processors (Multibeam, Lidar, Raster), etc. for the Fetchez ecosystem."
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version"]
requires-python = ">=3.12"
authors = [
    {name = "Matthew Love", email = "matthew.love@colorado.edu"},
    {name = "Christopher Amante", email = "christopher.amante@colorado.edu"},
    {name = "Elliot Lim", email = "elliot.lim@colorado.edu"},
    {name = "Michael MacFerrin", email = "michael.macferrin@colorado.edu"},
    {name = "Matt Fisher", email = "mfisher87@gmail.com"},
]
maintainers = [
    {name = "Matthew Love", email = "matthew.love@colorado.edu"},
]
keywords = ["geospatial", "fetchez", "multibeam", "lidar", "etl"]
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
    'Topic :: Scientific/Engineering :: GIS',
]

dependencies = [
    "fetchez>=0.8.8",
    "transformez>=0.6.2",
    "numpy>1.24",
    "scipy",
    "shapely>=2.0.0",
    "laspy[lazrs,laszip]",
    "rasterio>1.4.0",
    "geopandas>=1.0.0",
    "pyogrio>=0.7.0",
    "pandas",
    "pyproj>3.6.1",
    "pyshp",
    "matplotlib",
    "h5py",
    "click",
    "pyyaml",
    "requests",
]

[project.optional-dependencies]
gmt = ["pygmt"]
gdal = ["gdal"]
# naturalneighbor = ["naturalneighbor"]
interpolations = ["verde", "pykrige"]
ml = ["scikit-learn"]
h3 = ["h3"]
gui = ["ipyleaflet", "ipywidgets", "voila"]

full = ["globato[gmt,gdal,interpolations,ml,gui]"]

[dependency-groups]
dev = [
    "pre-commit",
    "mypy",
]
test = [
    "pytest",
    "pytest-cov",
    "requests-mock",
]
docs = [
    "sphinx<9.0.0",
    "sphinx-autodoc-typehints>=2.0.1",
    "sphinx-click>=6.0",
    "pydata-sphinx-theme",
    "myst-parser",
    "sphinxcontrib-mermaid"
]

[project.urls]
Homepage = "https://github.com/continuous-dems/globato"
Repository = "https://github.com/continuous-dems/globato"

[project.entry-points."fetchez.modules"]
globato_modules = "globato.modules"

[project.entry-points."fetchez.modules.bundles"]
globato_module_bundles = "globato.modules.bundles"

[project.entry-points."fetchez.hooks"]
globato_hooks = "globato.hooks"

[project.entry-points."fetchez.hooks.presets"]
globato_hook_presets = "globato.hooks.presets"

[project.entry-points."fetchez.recipes"]
globato_recipes = "globato.recipes"

[project.entry-points."fetchez.recipes.schemas"]
globato_recipe_schemas = "globato.recipes.schemas"

[project.entry-points."fetchez.recipes.modifiers"]
globato_recipe_schemas = "globato.recipes.modifiers"

[project.entry-points."fetchez.streams"]
globato_stream_readers = "globato.streams"

[project.entry-points."fetchez.streams.readers"]
globato_stream_readers = "globato.streams.readers"

[project.entry-points."fetchez.streams.profiles"]
globato_stream_profiles = "globato.streams.profiles"

# [project.entry-points."fetchez.plugins"]
# globato = "globato"

[project.scripts]
globato = "globato.cli:cli"
perspecto = "globato.cli.perspecto:perspecto_group"
dlim = "globato.cli.pointz:pointz_group"
gritz = "globato.cli.gritz:gritz_group"
wafflez = "globato.cli.build:build_cmd"

# --- Build configuration ---

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.version]
path = "src/globato/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/globato"]

[tool.hatch.build.targets.sdist]
include = [
  "src/globato",
  "tests",
  "CHANGELOG.md",
  "CITATION.cff",
  "CONTRIBUTING.md",
  "AUTHORS.md",
]
exclude = [
  ".github",
]

# --- Devtools configuration ---

[tool.mypy]
mypy_path = "src"
packages = ["globato"]
python_version = "3.12"
exclude = ["^build/", "^dist/", "^\\.venv/"]
disable_error_code = ["import-untyped"]
# strict = true

[[tool.mypy.overrides]]
module = [
    "matplotlib.*",
    "rasterio.*",
    "pyproj.*",
    "fetchez.*",
    "osgeo",
    "pygmt",
    "pykrige.*",
    "naturalneighbor",
    "sklearn.*",
    "verde",
    "h3",
    "h5netcdf.*",
    "polars",
    "netCDF4",
]
ignore_missing_imports = true
# follow_untyped_imports = true

[[tool.mypy.overrides]]
module = "scipy.*"
follow_untyped_imports = false
ignore_missing_imports = true

[tool.pytest.ini_options]
markers = [
    "health: marks tests that require live network access to external APIs (run with '-m health')"
]
filterwarnings = [
    "ignore::pydantic.warnings.PydanticDeprecatedSince20",
    "ignore:.*Support for class-based `config` is deprecated.*",
    "ignore::DeprecationWarning:planetary_computer.*"
]
