#!/usr/bin/env python

"""
globato.hooks.rasters.idw_surface
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Advanced Inverse-Distance-Weighted (IDW) interpolation.
Uses KDTree to solve IDW, but modifies the standard distance decay
by multiplying the geometric weights against the statistical Weight,
Confidence, and Uncertainty bands generated by the MultiStack accumulator.

:copyright: (c) 2016 - 2026 Regents of the University of Colorado
:license: MIT, see LICENSE for more details.
"""

import logging

import numpy as np
import rasterio
from rasterio.transform import xy
from scipy import spatial

from .base import RasterGlobalHook

logger = logging.getLogger(__name__)


class StatisticalInvdisttree:
    """Inverse-distance-weighted interpolation using KDTree, augmented with statistical metadata."""

    def __init__(
        self, coords, z_vals, w_vals=None, u_vals=None, c_vals=None, leafsize=10
    ):
        assert len(coords) == len(z_vals)
        self.tree = spatial.cKDTree(coords, leafsize=leafsize)
        self.z = z_vals

        self.w = w_vals if w_vals is not None else np.ones_like(z_vals)
        self.c = c_vals if c_vals is not None else np.ones_like(z_vals)
        self.u = u_vals if u_vals is not None else np.zeros_like(z_vals)

    def __call__(self, q_coords, nnear=8, eps=0.1, power=1.0, max_dist=np.inf):
        q_coords = np.asarray(q_coords)

        distances, indices = self.tree.query(
            q_coords, k=nnear, eps=eps, distance_upper_bound=max_dist
        )

        interpolated_z = np.zeros(len(distances))

        for i, (dist_array, idx_array) in enumerate(zip(distances, indices)):
            if np.any(np.isinf(dist_array)):
                # No points found within max_dist
                interpolated_z[i] = np.nan
                continue

            if dist_array[0] < 1e-10:
                # Query point is exactly on top of a data point
                interpolated_z[i] = self.z[idx_array[0]]
                continue

            # Standard Geometric Weight (Inverse Distance)
            geo_weights = 1.0 / (dist_array**power)

            # Apply Statistical Modifiers
            stats_w = self.w[idx_array]
            stats_c = self.c[idx_array]
            stats_u = self.u[idx_array]

            # Higher weight and confidence increases pull
            combined_weights = geo_weights * stats_w * stats_c

            # Higher uncertainty decreases pull (add epsilon to prevent div by zero)
            combined_weights *= 1.0 / (stats_u + 1e-6)

            # Normalize and solve
            combined_weights /= np.sum(combined_weights)
            interpolated_z[i] = np.dot(combined_weights, self.z[idx_array])

        return interpolated_z


class IDWSurface(RasterGlobalHook):
    """Interpolates a MultiStack using Statistical IDW.

    Args:
        power (float): Distance decay power (e.g., 1.0 for linear, 2.0 for gravity model).
        min_points (int): Number of nearest neighbors to query.
        radius (float): Maximum search radius in pixels.
    """

    name = "interp_idw"
    default_suffix = "_idw"
    meta_desc = "Intpolate NoData voids using IDW."
    meta_tags = ["globato", "interpolation", "multi-stack"]

    def __init__(self, power=2.0, min_points=8, radius=None, **kwargs):
        super().__init__(**kwargs)
        self.power = float(power)
        self.min_points = int(min_points)
        self.radius = np.inf if radius is None else float(radius)

    def process_raster(self, src_path, dst_path, entry):
        with rasterio.open(src_path) as src:
            is_stack = src.count >= 4
            if not is_stack:
                logger.warning(
                    f"[{self.name}] Input {src_path} is not a valid MultiStack. IDW requires Z, Count, Weight, and Uncertainty bands."
                )
                return False

            data_z = src.read(1)
            data_count = src.read(2)
            data_weight = src.read(3)
            data_uncert = src.read(4)
            # data_conf = src.read(X) # Add Confidence band reading if/when MultiStack generates it

            nodata = src.nodata if src.nodata is not None else -9999

            # Extract valid points (Count > 0)
            valid_mask = (data_count > 0) & (data_z != nodata) & (~np.isnan(data_z))

            if not np.any(valid_mask):
                logger.warning(f"[{self.name}] No valid data in {src_path}. Skipping.")
                return False

            rows, cols = np.where(valid_mask)
            z_vals = data_z[rows, cols]
            w_vals = data_weight[rows, cols]
            u_vals = data_uncert[rows, cols]

            # Convert pixel coords to true spatial coordinates
            x_vals, y_vals = xy(src.transform, rows, cols)
            coords = np.vstack((x_vals, y_vals)).T

            logger.info(
                f"[{self.name}] Building IDW KDTree with {len(z_vals)} points (Power: {self.power})..."
            )

            # Build the Tree
            idw_tree = StatisticalInvdisttree(
                coords, z_vals, w_vals=w_vals, u_vals=u_vals
            )

            # Predict over the full grid in manageable chunks to save RAM
            # Creating the prediction coordinates
            out_shape = data_z.shape
            result_arr = np.full(out_shape, nodata, dtype=np.float32)

            # Get real-world coords for every pixel in the target grid
            grid_cols, grid_rows = np.meshgrid(
                np.arange(out_shape[1]), np.arange(out_shape[0])
            )
            grid_x, grid_y = xy(src.transform, grid_rows.flatten(), grid_cols.flatten())
            grid_coords = np.vstack((grid_x, grid_y)).T

            logger.info(f"[{self.name}] Interpolating...")
            try:
                # Calculate max distance in real-world units based on pixel radius
                max_dist_units = (
                    self.radius * src.res[0] if self.radius != np.inf else np.inf
                )

                # Execute the IDW!
                predictions = idw_tree(
                    grid_coords,
                    nnear=self.min_points,
                    power=self.power,
                    max_dist=max_dist_units,
                )

                # Reshape back to the 2D grid
                result_arr = predictions.reshape(out_shape)

                # Replace NaNs with nodata
                result_arr[np.isnan(result_arr)] = nodata

                # Write to disk
                profile = src.profile.copy()
                profile.update(dtype=rasterio.float32, nodata=nodata, count=1)

                with rasterio.open(dst_path, "w", **profile) as dst:
                    dst.write(result_arr.astype(rasterio.float32), 1)

                logger.info(f"[{self.name}] Interpolation complete: {dst_path}")
                return True

            except Exception as e:
                logger.error(f"[{self.name}] IDW interpolation failed: {e}")
                return False
